import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import LeftPanel from "./components/LeftPanel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-y-hidden`}>
        <Navbar />
        <div className="flex items-stretch">
          <LeftPanel />
          <main className="grow bg-gray-200">{children}</main>
        </div>
      </body>
    </html>
  );
}
